---
# Team 20
# Team member: Site Huang, 908282
#              Chenyuan Zhang, 815901
#              Zixuan Zhang, 846305
#              Zhentao Zhang, 864735
#              Kangyun Dou, 740145

- name: Update apt package
  become: yes
  apt:
    name: ["apt"]
    state: latest

- name: Install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
  with_items:
    - python3-setuptools
    - python3-pip
    - curl
    - vim
    - apt-transport-https
    - ca-certificates
    - gnupg-agent
    - software-properties-common

- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Add Docker’s official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Configure Docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} edge"
    mode: '644'
    update_cache: yes
    state: present

- name: Install Docker
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Compose
  become: yes
  pip:
    name: ['docker-compose']
    executable: pip3
    version: 1.24.0
    state: present

- name: Create directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "{{home_dir}}"
    - "{{couchdb_dir}}"
    - "{{couchdb_data_dir}}"
    - "{{crawler_dir}}"
    - "{{couchdb_config_dir}}"
