- name: Create an instance on nectar
  hosts: localhost
  vars_files:
    - host_vars/vars.yml
  gather_facts: true

  roles:
    - role: common
    - role: images
    - role: volume
    - role: security_group
    - role: instance
    - role: volume_snapshot
  # environment
  #  http_proxy="http://wwwproxy.unimelb.edu.au:8000"
  #  https_proxy="http://wwwproxy.unimelb.edu.au:8000"
  #  ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"
