---

# - name: Update
#   become: yes
#   command: apt update


- name: Install pip3
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'



# - name: Install openstacksdk
#   become: yes
#   command: pip3 install python-openstackclient
