---
- name: create an instance
  os_server:
          name: '{{ instance_name }}'
          image: '{{ instance_image }}'
          key_name: '{{ instance_key_name }}'
          flavor: '{{ instance_flavor }}'
          availability_zone: '{{ availability_zone }}'
          security_groups: '{{ sg_names }}'
          network: '{{ instance_network }}'
          auto_floating_ip: yes
          wait: yes
          timeout: 600
          state: present
  register: os_instance
- debug:
        msg: "instance {{ instance_name }} has been created."
  when: os_instance.openstack is defined

- debug:
    var: openstack_server
